<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <!-- Required by the dotnet-ef tool to create migrations from this startup project -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoanDisbursement.Application\LoanDisbursement.Application.csproj" />
    <ProjectReference Include="..\LoanDisbursement.Infrastructure\LoanDisbursement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
